from enum import Enum


class StatutCompte(str, Enum):
    EN_ATTENTE = "EN_ATTENTE"
    ACTIF = "ACTIF"
    REFUSE = "REFUSE"


class StatutDemandeInscription(str, Enum):
    EN_ATTENTE = "EN_ATTENTE"
    ACCEPTEE = "ACCEPTEE"
    REFUSEE = "REFUSEE"


class StatutReservation(str, Enum):
    CONFIRMEE = "CONFIRMEE"
    ANNULEE = "ANNULEE"
    TERMINEE = "TERMINEE"


class StatutSalle(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class Role(str, Enum):
    UTILISATEUR = "utilisateur"
    ADMINISTRATEUR = "admin"


class ResultatVerification(str, Enum):
    ACCES_AUTORISE = "ACCES_AUTORISE"
    ACCES_REFUSE = "ACCES_REFUSE"


class TypeNotification(str, Enum):
    ACCEPTATION_INSCRIPTION = "ACCEPTATION_INSCRIPTION"
    REFUS_INSCRIPTION = "REFUS_INSCRIPTION"
    CONFIRMATION_RESERVATION = "CONFIRMATION_RESERVATION"
    MODIFICATION_RESERVATION = "MODIFICATION_RESERVATION"
    ANNULATION_RESERVATION = "ANNULATION_RESERVATION"
    COMPTE_ACTIVE = "COMPTE_ACTIVE"
    COMPTE_DESACTIVE = "COMPTE_DESACTIVE"
    PROMOTION_ADMIN = "PROMOTION_ADMIN"
    RETROGRADATION_ADMIN = "RETROGRADATION_ADMIN"
    ACCES_BATIMENT = "ACCES_BATIMENT"
